// Pharmacy domain constants — categories, units of measure, GST rates.

export const CATEGORIES: string[] = [
  "A TO Z",
  "ALZHEIMER DISEASE",
  "ANALGESIC / ANIPIRETIC",
  "ANALGESIC OPOID (NRx)",
  "ANALGESIC SPREY",
  "ANTACIDS & PPI",
  "ANTI ANXIETY (NRx DRUG)",
  "ANTI DIABETIC",
  "ANTI HYPERTENSION (B P)",
  "ANTI PARKINSON'S DIASEASE",
  "ANTIALLERGIC",
  "ANTIARRHYTHMIC",
  "ANTIBIOTICS",
  "ANTICOAGULANT",
  "ANTICOLD",
  "ANTICONVULSANT",
  "ANTIDEPRESSANT",
  "ANTIDIURETIC",
  "ANTIEMITTING",
  "ANTIEPILEPTIC",
  "ANTIFUNGAL",
  "ANTIHISTAMINE",
  "ANTIMUSCARINICS",
  "ANTISEPTIC",
  "ANTISPASMODIC",
  "ANTITHYROID",
  "ANTITUBERCULOSIS",
  "ANTIVIRAL",
  "AYURVEDIC",
  "BETA BLOCKER",
  "BIRTH CONTROL",
  "BLOOD THINNER",
  "BREATHING / ASTHMA",
  "CALCIUM",
  "CARDIOVASCULAR",
  "CHILD CARE",
  "COSMETICS",
  "COUGH SYRUP",
  "DERMATOLOGY",
  "DIABETIC CARE",
  "DIETARY SUPPLEMENT",
  "DIURETIC",
  "EAR DROPS",
  "ENZYME",
  "EYE DROPS",
  "FERTILITY",
  "FIRST AID",
  "GASTRO",
  "GENERAL",
  "GYNAECOLOGY",
  "HAIR CARE",
  "HEPATIC",
  "HORMONAL",
  "HYPNOTIC",
  "IMMUNOSUPPRESSANT",
  "INFANT NUTRITION",
  "INHALER / NEBULIZER",
  "INJECTION",
  "INSULIN",
  "IV FLUID",
  "LAXATIVE",
  "LIVER",
  "MULTI VITAMIN",
  "MUSCLE RELAXANT",
  "NASAL SPRAY",
  "NEUROLOGICAL",
  "NSAIDS",
  "NUTRITION",
  "ONCOLOGY",
  "ORAL CARE",
  "ORTHO CARE",
  "PAIN RELIEF",
  "PEDIATRIC",
  "PROBIOTIC",
  "PROTEIN",
  "RESPIRATORY",
  "SANITARY",
  "SKIN CARE",
  "STEROID",
  "SURGICAL",
  "SUPPOSITORY",
  "THYROID",
  "TONIC",
  "URINARY",
  "VITAMIN",
  "WOUND CARE",
];

export const UNITS: string[] = [
  "STRIP",
  "BOTTLE",
  "PACK",
  "JAR",
  "TABLET",
  "CAPSULES",
  "BOX",
  "TUBE",
  "PIECE",
  "VIAL",
  "INJ",
  "SACHET",
  "SPRAY BOTTLE",
  "CAN",
  "UNIT",
  "AMPULE",
  "DROP",
  "PACKET",
  "POUCH",
  "INSURANCE",
  "RESPULE",
  "AMPOULE",
  "GLOVES",
  "INSULIN",
  "VIAL & SMALL BOTTLE",
  "SYRINGE",
  "TIN",
  "CONTAINER",
  "SUPPOSITRIES",
  "ML",
  "INJECTION",
];

// GST rate options. Stored as a single combined % on the product;
// for CGST+SGST split this is divided by 2 at bill time.
export const GST_RATES: { label: string; value: number }[] = [
  { label: "Tax Free (0%)", value: 0 },
  { label: "GST 3%", value: 3 },
  { label: "GST 5%", value: 5 },
  { label: "GST 12%", value: 12 },
  { label: "GST 18%", value: 18 },
  { label: "GST 28%", value: 28 },
  { label: "GST 40%", value: 40 },
];
